safe:      true
future:    false
permalink: pretty
exclude:   [ README.md, Gemfile, vendor, .* ]

# Setup
title: "William Durand"
tagline: ""
description: |
  Hi! I'm <a href="https://mamot.fr/@willdurand">Will</a>.
  <br>
  <br>
  Lifelong learner. OSS evangelist. (Traveler.) Cyclist. (Runner.) (Speaker.) Firefox dev. He/him.
  <br>
  <br>
  <small>
  <a href="mailto:will@drnd.me">will@drnd.me</a> | 0xa509bcf1c1274f3b
  </small>

# Used in Atom feeds
url: "https://williamdurand.fr"

# About/contact
author:
  name: William Durand
  email: will@drnd.me
  twitter: couac
  github: willdurand
  mastodon: willdurand

twitter:
  username: couac
  card: summary_large_image

plugins:
  - jekyll-seo-tag
  - jekyll-redirect-from

repository: willdurand/willdurand.github.io
