safe:      true
permalink: pretty
exclude:   [ README.md, Gemfile, vendor, .* ]

# Setup
title: "William Durand"
tagline: ""
description: |
  Hi! I'm <a href="https://www.twitter.com/couac">Will</a>.
  <br>
  <br>
  Lifelong learner. OSS evangelist. (Traveler.) Cyclist. (Runner.) (Speaker.) Web worker at Mozilla. He/him.
  <br>
  <br>
  <small>
  <a href="mailto:will@drnd.me">will@drnd.me</a> | <a href="http://keys.gnupg.net/pks/lookup?search=0xA509BCF1C1274F3B&fingerprint=on">0xa509bcf1c1274f3b</a>
  </small>

# Used in Atom feeds
url: "https://williamdurand.fr"

# About/contact
author:
  name: William Durand
  email: will@drnd.me
  twitter: couac
  github: willdurand

twitter:
  username: couac
  card: summary_large_image

plugins:
  - jemoji
  - jekyll-seo-tag

repository: willdurand/willdurand.github.io
